name: Deploy on Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY_SERVER: ${{ secrets.SSH_PRIVATE_KEY_SERVER }}
      run: |
        echo "$SSH_PRIVATE_KEY_SERVER" > /tmp/server_keys
        echo "$SSH_PRIVATE_KEY_SERVER"
        chmod 600 /tmp/server_key
        ssh -i /tmp/server_key -o StrictHostKeyChecking=no ubuntu@35.162.38.244 'bash -s' < /home/ubuntu/deploy.sh
